### ISSUE TITLE
Official Release

### ISSUE THREAD

**Issue by bonham000** [FCC-Alumni/alumni-network#119]
**The Big One** 💥 💥 💥  🚀 

- [x] Create `Readme` & `Contributing` guides.
- [x] Solution for non-GitHub FCC users (aka who do they contact?)
- [x] Disable mock user generating code
- [x] Move all tabled features to a 'Post-Production' Issue [1].
- [x] Deployment:
   - [x] Buy domain from google domains, set up email forwarding, i.e. `staff@fcc-alumni.com`
   - [x] Configure a custom host url with Heroku? e.g. `https://www.fcc-alumni.com/`
   - [x] Heroku &/or mLab pan?
   - [x] Deploy updated app.
- [x] Announce with a Medium article, Forum post, and nice feature video (like the non-profits have).

***

**[[1] Post-Production Features](https://github.com/FCC-Alumni/alumni-network/issues/139)**

**Comment by bonham000** [comment]
@no-stack-dub-sack I think we are pretty close to initiating round II testing aka soft release with a small round of users. Maybe we can discuss this weekend.

**Comment by no-stack-dub-sack** [comment]
@bonham000 We are very close now! When #136 gets merged, for the most part what is left is article writing and readme and contributing guides - I think during round II testing would be a great time to accomplish this. How do you feel about WhiteListing some users so we can get them on board for testing, such as Quicny - who I'd love to show this to to help get him to share our Medium article when the time comes - and Chance, both of whom don't have any certs. 

Due to this issue, I've also been thinking of something over the last week or so - do you think maybe post-production we should think about a reputation/invite system where we can allow people into the community - being FCC members as an absolute baseline requirement... think about members like P1xt & Chance - P1xt who is basically a member _just to be_ a mentor. She's a prof dev who never felt the need to pursue a cert, but who would obviously be an asset to the community. And Chance, who is excellent and ramping up motivation, etc.

Maybe something like 3 invites from existing members could get you an honorary invitation... what do you think?

**Comment by bonham000** [comment]
@no-stack-dub-sack yes, we could whitelist those people and that would be a good way to test the whitelist. And yeah, an invitation system might be a cool feature to add for the reasons you mentioned as well. Chance doesn't have any FCC certs yet?

**Comment by no-stack-dub-sack** [comment]
@bonham000 haha, no he does not, I think running the cohorts kind of took over for him. But his talents are really coming out there, so it is a good thing - fcc leads everyone to their strengths in some way or another! There's certainly room in the tech world for that sort of leadership/organization. In fact, I think he's mentioned the idea of pursuing project management or something before. 

But cool, glad you'd be on board with the invitation system. We'd have to make some changes around that, so def def def a post-production thing, but worth entertaining. I'll add it to the list.

**Comment by no-stack-dub-sack** [comment]
@bonham000 Almost ready to resolve this one! One checkbox left...

**Comment by bonham000** [comment]
@no-stack-dub-sack looking good! Pretty much ready to pull the trigger. It would be great if this thing actually gains some traction in the community once we release it.

**Comment by no-stack-dub-sack** [comment]
@bonham000 closing this issue for obvious reasons :smile: 

Job well done!

**Comment by bonham000** [comment]
@no-stack-dub-sack 🎉  🎉  🎉
