### ISSUE TITLE
Save profile preferences before linking social media

### ISSUE THREAD

**Issue by bonham000** [FCC-Alumni/alumni-network#141]
**This issue is for tracking anything that comes up in the soft release.**

**Beta Users:** Please report any bugs or issues you may uncover, ideas for improvements, or feedback on the app as a whole here.

**Thank you!!!** — _the FCCAN team_

**Comment by bonham000** [comment]
@no-stack-dub-sack  **Bug (?):** On the profile preferences page, if you complete fields and then try to add your Twitter or LinkedIn without saving your fields, you will lose all progress because the page redirects. Maybe we can try to save the current fields before trying to authenticate?

**Comment by no-stack-dub-sack** [comment]
@bonham000 good call - I did know this, and so have just been saving before doing that to avoid it, but of course, I've only been doing that because I know. Should've thought of this earlier. I can def make that happen. I have something similar happening with the repos section, those autosave as you go

**Comment by bonham000** [comment]
I'll just rename this to track this one issue.

**Comment by no-stack-dub-sack** [comment]
@bonham000 this is resolved by the way, so going ahead and closing it.
