### ISSUE TITLE
mentorship search function does not behave as expected

### ISSUE THREAD

**Issue by Kornil** [FCC-Alumni/alumni-network#153]
searching for "as" on the mentorship tab just removes one user from the search results for no apparent reason, except from one profile no one has a substring containing "as" in the profile, as you can see from the sceenshot.

![search_bug](https://cloud.githubusercontent.com/assets/11630180/25917514/9f1eca72-35c8-11e7-9160-ac6a79f8c518.png)

**Comment by no-stack-dub-sack** [comment]
@Kornil So this is probably because you are on the default "all" search. Which is searching a lot more than what is viewable here... If you open the dropdown, you can see all the different categories that "all" is searching through, and can also narrow it down accordingly. 

We've been dreaming of a feature that will return the matched result to show the searcher what exactly has matched, and seeing this feedback tells me that it is probably pretty important. So this is definitely something to keep in mind. 

Let me know if you think there is still something else going on here

**Comment by no-stack-dub-sack** [comment]
@Kornil I forget if we ever talked about this one again - did this make sense and / or address your concerns?

**Comment by no-stack-dub-sack** [comment]
I am resolving this for now as I believe the search functionality works mostly as expected... Still needs some work, but can be done post prod.
