### ISSUE TITLE
Inactive users (mentors/mentees)

### ISSUE THREAD

**Issue by Matthew-Burfield** [FCC-Alumni/alumni-network#160]
This definitely isn't an issue for right now, but when filtering on mentors/mentees, I'd like to be able to filter based on how active they are or when they last logged in.

Or at least be able to view this information

**Comment by smiller171** [comment]
@Matthew-Burfield I'm not sure how relevant that information would be. At this time most mentor-mentee communication would happen off-site, and just having your profile up would allow people to reach out to you through many other channels.

**Comment by Matthew-Burfield** [comment]
I was more talking about people that have signed up, and maybe was a mentor for a while, but then stopped for whatever reason and haven't been mentoring anyone for 6 months or so. As a user, I wouldn't want to waste my time reaching out to people that are no longer active/aren't going to reply.

**Comment by smiller171** [comment]
@Matthew-Burfield What I'm saying is, the way the site is currently set up, it's possible for a user to be an active mentor perpetually without visiting the site if people find their profile and reach out through methods other than the built-in chat, since you can leave info like email for contact. fcc-alumni has no way of knowing if that person is active through other channels after being discovered on the website.

You might be able to get around this by implementing a rating system of some kind

**Comment by no-stack-dub-sack** [comment]
@smiller171 yeah, we've considered a rating system of some sort as well, but back burner for now I think. I think adding Gitter will really help us find out if people will actually use this site, and then we'll go from there.

**Comment by stephenjfox** [comment]
@no-stack-dub-sack @smiller171 would a sorting system suffice for a first stab at things?
If you sorted by the "last date active" - or if the search results were just defaulted to show the "most recent activity" metric next to the result - wouldn't this problem go away?

**Comment by smiller171** [comment]
@stephenjfox I don't think it would help, because the crux of the problem is that login activity is a poor indicator of how active a mentor is if they are responding to messages on Gitter or email without ever logging back into FCC-alumni. There's not enough activity yet to get data on whether that is common or not.

**Comment by no-stack-dub-sack** [comment]
@stephenjfox @smiller171 I think everyone is inactive right now ☹️ 

so I don't know if this is something we need to worry about just yet. I'm closing this and will add it to a "closed issues that are still good ideas for if we ever pick up steam" issue.

**Comment by stephenjfox** [comment]
All the users have gone inactive? 😲
We gotta start this back up!

2017년 11월 8일 (수) 오후 8:28, Peter Weinberg <notifications@github.com>님이 작성:
