### ISSUE TITLE
Add CI support

### ISSUE THREAD

**Issue by theodesp** [FCC-Alumni/alumni-network#189]
Currently I don't see a Continuous integration pipeline and its imperative to add one as the project evolves.

Some choices are:

[travis](https://travis-ci.org/) - Very popular.
[Circle](https://circleci.com/) - Another good choice.
[codeship](https://codeship.com/) - Another choice.
[werker](http://www.wercker.com/) - This one is from Oracle.

I suggest we choose one and set it up for the project.

**Comment by no-stack-dub-sack** [comment]
Agreed - while it was only 2 working on it, not so essential, if people actually begin jumping in and contributing, this will be great. We'd also like to add custom JSLint built into the CI, but for right now, the only way I can see to do that is to eject from CRA, which is not ideal. See #186

**Comment by theodesp** [comment]
I would argue that adding a CI builds confidence and at some point, collaborators need to be able to push code without breaking the build and not knowing about it. So it's a good idea to incorporate it as part of the development. That also leads to a proactive monitoring of the application status.

**Comment by smiller171** [comment]
@no-stack-dub-sack I'm not sure what CRA is, but I very much doubt it would prevent proper application of linting. Would be willing to help out with CI integration as part of the infrastructure work we talked about in another issue

**Comment by smiller171** [comment]
as @theodesp alludes to, it brings a sense of professionalism and makes it more approachable for developers to submit PRs.

**Comment by no-stack-dub-sack** [comment]
@theodesp @smiller171 Cool! I'd appreciate the guidance, as I am still fairly new at all of this. Your points do make sense and I am definitely up to adding this. 

@smiller171 CRA is [Create-React-App](https://github.com/facebookincubator/create-react-app), which is a boilerplate for React projects built by FaceBook. It allows you to skip the arduous setup process with webpack, etc. and lets you jump right in. ESLint is built into the project, but its settings are hardcoded into the config files. In order to access and modify them you need to ["eject"](https://github.com/facebookincubator/create-react-app#converting-to-a-custom-setup) from CRA, which makes the project a lot bulkier and reveals all the confusing webpack configs etc. Once done, this cannot be undone. 

If you want, you can see what I mean on your fork of the project. It would just have to be deleted and re-installed afterwards since any PRs after that would be void until we make the decision one way or the other to do this or not.

**Comment by smiller171** [comment]
@no-stack-dub-sack It's possible the CI tool could be set up to ignore the CRA eslint config and use yours instead. Worth looking into. Could also just use a different linter if for some reason that's not possible.

**Comment by no-stack-dub-sack** [comment]
@smiller171 yeah, I was thinking the same thing about a different linter. Looking forward to creating the CI workflow - I thought of another very good use case for this today. 

We have a way to allow anyone in to the app for dev that way people who are not certified can still contribute if they want, but this counts on this code being reverted before any PR. With CI, would we be able to check that a specific line of code remains unchanged?

**Comment by smiller171** [comment]
Yes you could, but there are also better ways to do it, such as setting an environment variable when you run the code to enable dev mode instead of changing a setting in a file

**Comment by smiller171** [comment]
fixed by #224

**Comment by smiller171** [comment]
#224 adds CircleCI, using Circle 2.0

Need to add tests for CI to be useful
