### ISSUE TITLE
Collaboration Section - create better UI/UX for adding projects

### ISSUE THREAD

**Issue by gwenf** [FCC-Alumni/alumni-network#191]
I can't seem to save a path to a github project.

Sometimes, it will say that it's saved and sometimes it will say there is a problem with the path or it's a private repo (it's not really) but it never actually saves.

<img width="404" alt="screen shot 2017-06-25 at 2 49 51 pm" src="https://user-images.githubusercontent.com/10039233/27518790-ddc756e8-59b5-11e7-8785-17476c7de52a.png">

Have you been able to save one before?

**Comment by no-stack-dub-sack** [comment]
@gwenf interesting. Have you tried other repos or is the problem localized to this one?

**Comment by gwenf** [comment]
I've tried a few different repos, including my fork of the main FCC repo but I can't get it to save. I can try to look into the code at it.

@no-stack-dub-sack I have a question about running the project locally though.
I have all four tabs terminal tabs open and running and I followed the instructions in the readme. http://localhost:3000 loads fine and I can click on `login`.
However, I have the following issue when I click on button to login with github:
`https://localhost:8080/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch`

The `.env` file is set up correctly. Why does it change from port 3000 to 8080? And do you know anything about the above issue?

**Comment by no-stack-dub-sack** [comment]
@gwenf just for kicks, can you try adding the main FCC repo itself? If you're listed as a contributor that should also work. It's strange that it's not working for you.

As per your other question - yes, this is an issue we've struggled with routinely, for different reasons. But in this case - the server is running on a separate port than the client, so anything server should be running on `8080` while the CRA client dev server is running `3000`. 

In your OAuth settings on github, do you have the callback URL set to `http://localhost:80808/auth/github/callback`?

That should do it... let me know if this works!

**Comment by gwenf** [comment]
I had that as the callback already.
I forked and cloned the repo again and I'm still getting the same error.

I'll try to figure this out this week unless you have another idea about what it might be.

**Comment by gwenf** [comment]
@no-stack-dub-sack would you be able to take a screen shot and show me where the projects would appear in the application once you have added them correctly?

**Comment by no-stack-dub-sack** [comment]
@gwenf Sure! 

So this is what it looks like from "Preferences" view:
![image](https://user-images.githubusercontent.com/18563015/27555442-bdeb4f58-5a7f-11e7-9c7f-ba4519eb71c5.png)

And from "Public" view:
![image](https://user-images.githubusercontent.com/18563015/27555481-df765802-5a7f-11e7-890f-cfb529df3544.png)

Also note that unlike any other section - as soon as a project is added, it should be saved in your user object automatically. This is one of the more tedious sections to fill out, so if someone added a bunch and then tried to add their Twitter without first saving, all that progress would be erased and that would be annoying, so I set this one up a bit differently. 

Interested to see if you can get to the bottom of this since for now this seems to be isolated to you (or at least you're the only one who's reported it) - it's very strange. I just tested all mine again too. 

I'd like this section to be super seamless, I eventually envision the ability to add tags to projects since we'd like to add a new section that let's users search through other users projects. This is actually pretty high priority, since right now the only way to find them is to go user by user - not cool. 

See #157

**Comment by patricksevat** [comment]
I'm having issues when adding my bitbucket repo. I'm using a general namespace rather than a specific project. On my bio the link appears, but rather than bitbucket it is shown as a github link.

When I navigate to preferences the collaboration section is empty

**Comment by gwenf** [comment]
Ok. I get it now. So you have to click enter basically.
Save doesn't do anything in that section. There should be some note there to let people know maybe. It's confusing that there is a save icon above there that doesn't save it.

Also, the `SAVE_USER` action doesn't get fired if there is another problem on the page and it doesn't give you an error either. Only if there are no other errors does it save on pressing enter.

Also, it's saying some repo's are private when they aren't.

**Comment by no-stack-dub-sack** [comment]
@patricksevat Can you clarify what you mean by that? In other words, you're trying to add your entire bitbucket namespace rather than a specific project? Not sure it will work like that, it should be for repos for specific projects. That said, I haven't experimented too much with bitbucket since I don't have any repos there other than the ones I created to test this feature.

@gwenf Yeah, I can see that. Maybe I'll just get rid of the save button altogether there. But the errors thing was unforeseen on my part and a good point. I will have to think about this.

**Comment by patricksevat** [comment]
@no-stack-dub-sack Ah I see. Missed the above comment by @gwenf that you need to hit enter. I get a validation error when trying to enter namespace. The label is a bit misleading ;]. Also i expected that the save button at the end of the page\form would save whatever I have entered (without having hit the enter key).

**Comment by gwenf** [comment]
Yes, I think we need a plus button or something to prompt the user to add the repo. Otherwise they might just think it's not working.

**Comment by no-stack-dub-sack** [comment]
@gwenf @patricksevat Ok, great. This is good feedback, stuff that I couldn't see as the creator, so great to have this input. 

I've opened this up Help Wanted to see if anyone is willing to take it on. Otherwise, I'll be happy to make the improvement myself if no one else jumps in (want to give it some time to see if we can spark some outside collaboration). 

The specific task - make the UI/UX around adding repos more clear:
- eliminate the save button
- create a plus/submit button to make it clear how to add projects

Other issues will be to look into validations (why some repos that aren't private are showing up as private), fix the errors issues mentioned by @gwenf, make labels less misleading?

**Comment by gwenf** [comment]
I started digging through those components last night and I think there is some general cleaning up needed. I'll see what I can do.

**Comment by no-stack-dub-sack** [comment]
@gwenf Sweet! Yes, I can def agree with that. Thanks and let me know!

**Comment by gwenf** [comment]
@no-stack-dub-sack let me know what you think about the PR I made.

**Comment by gwenf** [comment]
I'm closing this since the PR was merged.
