### ISSUE TITLE
[Profile] Jobs Section | Add previous jobs

### ISSUE THREAD

**Issue by AkiraLaine** [FCC-Alumni/alumni-network#193]
Hey! This is a pretty awesome app :smile:

I feel like adding a 'previous jobs' section would be nice. For example, on the mentorship page, selecting "professional developers only" doesn't show anyone who isn't currently employed. But you still might have worked professionally (hence, you're a professional).

Hope that makes sense.

**Comment by no-stack-dub-sack** [comment]
@AkiraLaine this is a good point. Something we can definitely think about. Maybe simply rewording the question rather than adding a section for previous jobs, which could get lengthy in some cases. 

What are your thoughts about that? Is this something you'd be willing to contribute on?

**Comment by AkiraLaine** [comment]
Maybe instead of:
> Are you employed as a software developer?

We could say

> Are you or have you been employed as a software developer?

Then if the answer is *yes*, we show the following:
- Place of employment
- Position
- Start Date
- Do you currently work here?
  * yes: show the result as `Start Date - Present`
  * no: enter End Date

And yes, I would love to work on it 😄

**Comment by no-stack-dub-sack** [comment]
@AkiraLaine Nice! Glad you got things up and running! Hope the guide was helpful. 

This sounds good, but what if someone has had more than one recent role, like if they were a consultant or something and had several in the last year or 2.

What if we just said:

> Are you or have you been employed as a software developer?

If yes:

> Most recent company:

And leave it at that? Not as specific, but it avoids opening up a larger can of worms of wanting to list all previous employment.

Or we could just do if yes:

> Companies: 

And have them list companies, in case someone worked at Google or something a while back and wants to highlight that. I just don't want it to become a full on resume, and since there's at least partial LinkedIn integration (not perfect right now) I think we can leave to full job history details to them.

**Comment by AkiraLaine** [comment]
Hey @no-stack-dub-sack 

So I took your suggestion. Makes things easier, and you're right, no need to turn this into a resume :stuck_out_tongue:

Anyways, here are screenshots of what the UI looks like now

*Currently Working*
![image](https://user-images.githubusercontent.com/11958359/27671504-ea68fa32-5cdf-11e7-90fa-577663f8f9c2.png)

![image](https://user-images.githubusercontent.com/11958359/27671628-b97f4786-5ce0-11e7-84e6-09402bf18aed.png)

*Not currently working but has worked professionally*
![image](https://user-images.githubusercontent.com/11958359/27671508-f1677232-5cdf-11e7-9214-d9fb22366864.png)

![image](https://user-images.githubusercontent.com/11958359/27671618-a6ffbd70-5ce0-11e7-826f-af8503ffa65b.png)

*Never worked*
![image](https://user-images.githubusercontent.com/11958359/27671537-2b8e5a5c-5ce0-11e7-9527-35a8af8e36f7.png)

As for the 'currently working', do you think we should have 'Currently working for' and a 'previously worked for' section or leave it as is?
