### ISSUE TITLE
Searching and Discovering Collaboration Projects

### ISSUE THREAD

**Issue by gwenf** [FCC-Alumni/alumni-network#218]
I feel like there should be a way for users to search through and discover projects to collaborate on (search by technology or type of project or keywords). Maybe, we could add the search feature next to the filters for mentors, mentees, etc.

Only a portion of the profile information can be used right now to search through and connect members. Any thoughts?

**Comment by no-stack-dub-sack** [comment]
@gwenf for sure, this is actually very similar to #157 and we have definitely had this in mind for a while. I would definitely love to get this feature set up. 

As for the profile information, just about every piece of it should be searchable. There might be one or 2 pieces that aren't though. But you can either select "all" or narrow it down more specifically, but all should search through skills, interests, bio, mentorship bio, location, username,  (not sure about company, would have to look), and I think a few other things. I believe all the code works as expected, but that said, there are definitely better options as far as making things searchable. I just wrote a quick filter function that iterates through all the text, selectively for each section, or through every section if "all" is selected. I don't know if something like elastic search could possibly be integrated though?

One other thing I'd also like to implement (which is buried somewhere in some issue, prob #139) is highlighting text for which parts of the profile have actually matched, i.e. showing the user exactly where the match is in each profile, rather than just showing the matched users.

**Comment by gwenf** [comment]
@no-stack-dub-sack hey, I'm speaking at a conference on Monday and Tuesday, so I'm going to start working on this issue after I get back from that.

**Comment by gwenf** [comment]
@no-stack-dub-sack I'm digging through the github api and see what metadata we could pull to be able to search for projects (eg technologies used or license maybe).
Let me know if you have input on this.

**Comment by no-stack-dub-sack** [comment]
@gwenf wow, I'm sorry, I totally dropped the ball on this one. I somehow missed these comments and thought I hadn't heard from you on this. 

As an update, @Christian-Paul made some pretty solid progress on this with a api he developed that  would return a lot of the info we would need, now its about implementing it:

https://repo-info.herokuapp.com/
https://github.com/Christian-Paul/repo-info

That said, activity has seemed to taper off here quite a bit, and I'm not sure if I want to ask him or anyone else to contribute a significant amount of time into implementing something that might never get used 🙁 , so not quite sure what the best thing to do is from here. 

If case you don't see my comment from another issue, have you found occasion to visit the app lately by any chance?

Also, just curious, what conference did you speak at, and how did it go!?

**Comment by gwenf** [comment]
@no-stack-dub-sack Hey! The conference was in Des Moines and it went really well. I've been slammed with workshops for the local FCC group too but I love doing those.

I have visited the app a few times here and there. Are you still going to continue development on here?

I think that this app would be useful if people could do things like find pairing partners and projects to collaborate on - some of the things that I remember were discussed before.
