### ISSUE TITLE
Add automated updates and regression checker for NPM packages via Greenkeeper

### ISSUE THREAD

**Issue by theodesp** [FCC-Alumni/alumni-network#230]
This is just a suggestion but it really helps to keep track of how far we are in terms of dependencies updates.

Now that we have a CI we can use Greenkeeper to automate the process of checking if an update to our dependencies will break the build.

Check out their website https://greenkeeper.io/

**Comment by smiller171** [comment]
@theodesp I don't think this would actually be safe to adopt until there is a decent test suite. Right now CI is just checking for linter errors.

**Comment by no-stack-dub-sack** [comment]
@theodesp I think this is a great idea! and sorry for the late reply. 

@smiller171 why would it be unsafe to include this until there is better test coverage (or... test coverage)?

**Comment by smiller171** [comment]
@no-stack-dub-sack because the way it works is when there is a new update to a package, it updates the package and runs your tests. If all the tests pass, it commits that change. If the tests fail it rolls it back. In that way it keeps you in the most up-to-date compatible packages. If you don't have good test coverage, it won't be able to identify breaking changes.

**Comment by no-stack-dub-sack** [comment]
@smiller171 ahh, that makes sense. We shall put this on hold for the time being then.
