### ISSUE TITLE
fix docker setup script to be cross-platform friendly

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#259]
In reference to @Christian-Paul's difficulty in setting up the project locally. Current setup script needs bash environment. Ideally, we should be changing the script to run on windows machines as well as unix/linux-based platforms. All you @smiller171! Thanks!

**Comment by smiller171** [comment]
update: docker-toolbox won't accept a windows-format file path as an argument for mounting volumes. I believe the best path forward is to require Linux Subsystem for Windows or Cygwin/Babun. Seeking approval to go down this path as it means greater initial setup for Windows developers who don't already use these tools.

Alternatively, some solution would need to be found for getting the current dir in the format Docker Toolbox needs, which may mean writing a batch script to do a conversion and save the variable. This would take much more effort and has potential to break down the line.

As a last resort we could scale back the dependency on Docker for development and use it just for running external dependencies like Mongo. This increases the risk of incompatibilities introduced by developing on completely different platforms, and there's no way of predicting what node packages may not work properly on Windows down the line.

**Comment by smiller171** [comment]
As more issues with Docker on Windows pop up, it may be time to throw in the towel and go back to running natively, at least in part. Turns out inotify will not work with volumes mounted in Windows, which means a workaround would be needed for auto-reload to work.

At this point I think the only good options are to reduce the reliance on Docker for the dev environment, or to impose that all development be done on *nix (which could be accomplished through a cloud IDE or a VM)

Your call @no-stack-dub-sack

**Comment by no-stack-dub-sack** [comment]
@smiller171 I honestly almost like the VM option better, only because I really like the docker functionality and we don't have too many contributors right now to displease... but on the other hand it does make the project much less approachable in the future.
